# Conexion mysql

# spring.datasource.url=jdbc:mysql://mysql_spring_angular:3306/inventario_db?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=admin123456
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# -------------------------------------------------------------------------
# -----------------------------------------  AQUI EMPEZAMOS              --------------------------
# -----------------------------------------------------------------------------------
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
# spring.datasource.username=${MYSQL_USERNAME:root}
# spring.datasource.password=${MYSQL_PASSWORD:123456admin}
# spring.jpa.show-sql=true
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# server.port=8081
server:
  port: 8080
  
spring:
  application:
    name: proyect-angular
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}    
    password: ${MYSQL_PASSWORD:123456admin}
    
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

